#!/bin/sh
# postinst script for fnkey
#
# see: dh_installdeb(1)

set -e
KVER=`uname -r`

case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
