#!/bin/sh
# postrm script for fnkey
#
# see: dh_installdeb(1)

set -e

KVER=`uname -r`

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	ldconfig
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
